# Generated by Django 5.0.2 on 2025-05-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerbit', models.CharField(max_length=200)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Penerbit',
                'ordering': ['nama_penerbit'],
            },
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('asal_negara', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Penulis',
                'ordering': ['nama_belakang', 'nama_depan'],
            },
        ),
        migrations.CreateModel(
            name='RakBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rak', models.CharField(max_length=100)),
                ('lokasi_rak', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rak Buku',
                'ordering': ['nama_rak'],
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tahun_terbit', models.IntegerField()),
                ('genre', models.CharField(blank=True, choices=[('FIKSI', 'Fiksi'), ('NONFIKSI', 'Non-Fiksi'), ('SASTRA', 'Sastra'), ('SEJARAH', 'Sejarah'), ('SAINS', 'Sains'), ('TEKNOLOGI', 'Teknologi'), ('BISNIS', 'Bisnis'), ('LAINNYA', 'Lainnya')], max_length=20, null=True)),
                ('jumlah_halaman', models.IntegerField(blank=True, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buku', to='buku.penerbit')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buku', to='buku.penulis')),
            ],
            options={
                'verbose_name_plural': 'Buku',
                'ordering': ['judul'],
            },
        ),
        migrations.CreateModel(
            name='PenempatanBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.buku')),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.rakbuku')),
            ],
            options={
                'verbose_name_plural': 'Penempatan Buku',
                'ordering': ['-tanggal_ditambahkan'],
                'unique_together': {('buku', 'rak')},
            },
        ),
        migrations.AddField(
            model_name='buku',
            name='rak',
            field=models.ManyToManyField(related_name='buku', through='buku.PenempatanBuku', to='buku.rakbuku'),
        ),
    ]
