# Generated by Django 5.0.2 on 2025-05-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakbuku',
            name='kapasitas',
            field=models.PositiveIntegerField(default=100, help_text='Jumlah maksimum buku yang dapat ditampung'),
        ),
    ]
