# Generated by Django 5.0.2 on 2025-05-28 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_rakbuku_kapasitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penempatanbuku',
            name='rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan', to='buku.rakbuku'),
        ),
    ]
